language: python
python:
  - "3.5"

addons:
  chrome: stable

before_install:
  - sudo apt-get install chromium-chromedriver
  - export PATH=$PATH:/usr/lib/chromium-browser/
#command to install dependencies
install:
  - pip install -r requirements.txt
#command to run tests
script:
  - pytest
